export const menulist = [
    { title: 'Моя работа', subItems: [] },
    { title: 'Структура портала', subItems: [] },
    { title: 'Личное расписание', subItems: [] },
    { title: 'Отсутствие на рабочем месте', subItems: [] },
    { title: 'Портфель услуг', subItems: [] },
    { title: 'Дашборды', subItems: [] },
    { title: 'Доски задач', subItems: [] },
    { title: 'Обращения', subItems: [] },
    { title: 'События', subItems: [] },
    { title: 'Инциденты', subItems: [] },
    { title: 'Проблемы', subItems: [] },
    { title: 'Настройка каталогов', subItems: [] },
    { title: 'Запросы на обслуживание', subItems: [] },
    { title: 'Запросы на изменение', subItems: [] },
    { title: 'Управление конфигурациями', subItems: [] },
    { title: 'Управление уровнем услуг', subItems: [] },
    { title: 'Настройка соответствий', subItems: [] },
]
